import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import Breadcrumb from "../components/Breadcrum";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          <Sidebar />
          <div className="flex-1 p-6">
            <Breadcrumb />
            <div className="mt-4 p-4 bg-white shadow rounded-lg">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}